Repository okp4/portal-web, pull requests merged in 2022-10, with the labels that each got.

#30 feat: add home page
  package.json
  src/components/dataspaceDashboard/dataspaceEntities/DataspaceEntities.tsx
  src/components/dataspaceDashboard/dataspaceEntities/dataspaceEntities.scss
  src/components/dataspaceDashboard/dataspaceOptions/DataspaceOptions.tsx
  src/components/dataspaceDashboard/dataspaceOptions/dataspaceOptions.scss
  src/components/dataspaceDashboard/dataspaceSummary/DataspaceSummary.tsx
  src/components/dataspaceDashboard/dataspaceSummary/dataspaceSummary.scss
  src/components/index.ts
  src/i18n/dashboard/dashboard_en.json
  src/i18n/dashboard/dashboard_fr.json
  src/i18n/footer/footer_en.json
  src/i18n/footer/footer_fr.json
  src/i18n/index.ts
  src/pages/api/fakeData/dataspaces.ts
  src/pages/api/fakeData/dataspaces/[id].ts
  src/pages/home/home.scss
  src/pages/home/index.tsx
  src/pages/index.tsx
  src/pages/styles.scss
Labels: enhancement

#67 Fix: fix overlapping dataspace description on safari
  src/components/dataspaceDashboard/dataspaceSummary/dataspaceSummary.scss
Labels: bug

#69 Chore(dev-deps): bump @okp4/ui to v2
  package.json
  yarn.lock
Labels: dependencies

#64 Feat: replace add dataspace button by see governance button
  .env.development
  Dockerfile
  environment.d.ts
  src/components/dataspaceDashboard/dataspaceSummary/DataspaceSummary.tsx
  src/components/dataspaceDashboard/dataspaceSummary/dataspaceSummary.scss
  src/i18n/dashboard/dashboard_en.json
  src/i18n/dashboard/dashboard_fr.json
  src/pages/api/fakeData/dataspaces/[id].ts
  src/pages/home/index.tsx
  src/pages/index.scss
  src/pages/index.tsx
Labels: enhancement

#65 Refactor: change dataspace creation button location
  src/components/dataspaceDashboard/dataspaceSummary/DataspaceSummary.tsx
  src/components/dataspaceDashboard/dataspaceSummary/dataspaceSummary.scss
  src/components/layout/layout.scss
Labels: enhancement

#84 Feat/reverse dashboard options & entities
  src/components/dataspaceDashboard/dataspaceEntities/dataspaceEntities.scss
  src/components/dataspaceDashboard/dataspaceOptions/dataspaceOptions.scss
  src/components/dataspaceDashboard/dataspaceSummary/dataspaceSummary.scss
  src/pages/index.scss
  src/pages/index.tsx
Labels: enhancement

#81 Feat/add header navigation menu
  .env.development
  Dockerfile
  environment.d.ts
  src/components/layout/Layout.tsx
  src/components/layout/layout.scss
  src/i18n/header/header_en.json
  src/i18n/header/header_fr.json
  src/i18n/index.ts
  src/pages/api/config.ts
Labels: enhancement, dependencies

#88 Add explore page
  .env.development
  Dockerfile
  environment.d.ts
  src/components/explore/exploreFilters/ExploreFilters.tsx
  src/components/explore/exploreList/ExploreList.tsx
  src/components/explore/exploreList/exploreList.scss
  src/components/explore/exploreListConfiguration/ExploreListConfiguration.tsx
  src/components/explore/exploreListConfiguration/exploreListConfiguration.scss
  src/components/index.ts
  src/components/pageTitle/PageTitle.tsx
  src/components/pageTitle/pageTitle.scss
  src/dto/DatasetDto.ts
  src/dto/DataspaceDto.ts
  src/dto/ServiceDto.ts
  src/i18n/explore/explore_en.json
  src/i18n/explore/explore_fr.json
  src/i18n/index.ts
  src/pages/api/config.ts
  src/pages/api/dataverse/dataset/index.ts
  src/pages/api/dataverse/dataspace/[dataspaceId]/service/[serviceId].ts
  src/pages/api/dataverse/dataspace/[dataspaceId]/service/index.ts
  src/pages/api/dataverse/service/index.ts
  src/pages/dataverse/explore/explore.scss
  src/pages/dataverse/explore/index.tsx
  src/pages/styles.scss
  src/utils.ts
Labels: enhancement

#32 feat: add the dataset page with fake data
  .env.development
  data/dataset.json
  next.config.mjs
  src/components/dataset/datasetInformation/DatasetInformation.tsx
  src/components/dataset/datasetInformation/datasetInformation.scss
  src/components/dataset/datasetPreview/DatasetPreview.tsx
  src/components/dataset/datasetPreview/datasetPreview.scss
  src/components/explore/exploreList/ExploreList.tsx
  src/components/index.ts
  src/components/pageTitle/PageTitle.tsx
  src/components/pageTitle/pageTitle.scss
  src/components/previousPageButton/PreviousPageButton.tsx
  src/dto/DatasetDto.ts
  src/i18n/dataset/dataset_en.json
  src/i18n/dataset/dataset_fr.json
  src/i18n/explore/explore_en.json
  src/i18n/explore/explore_fr.json
  src/i18n/index.ts
  src/pages/api/fakeData/dataspaces.ts
  src/pages/api/fakeData/dataspaces/[id].ts
  src/pages/dataverse/explore/dataspace/[dataspaceId]/dataset/[datasetId].tsx
  src/pages/dataverse/explore/dataspace/[dataspaceId]/dataset/datasetId.scss
  src/utils.ts
  yarn.lock
Labels: enhancement
